### ISSUE TITLE
Server doesnt seem to run

### ISSUE THREAD

**Issue by FBurner** [rowanhill/wiremock-php#14]
I just do as in the readme with php 7.2

but get this notice  Trying to get property 'id' of non-object in [ some/folder/]Client/Wiremock.php on line 61

and if i access localhost:8080 but no response or anything 

declare(strict_types=1);

namespace [Some\NameSpace]\MockServer;

use WireMock\Client\WireMock;

chdir(dirname(__DIR__));

require_once 'vendor/autoload.php';

$wireMock = WireMock::create('localhost', 8080);

$wireMock->stubFor(
    WireMock::get(
        WireMock::urlEqualTo('/myRoute')
    )->willReturn(
        WireMock::aResponse()
            ->withHeader(
                'Content-Type', 'text/plain'

            )
            ->withBody('Hello world!')
    )
);

while (true) {
   echo 'server running';
   sleep(5);
}

**Comment by joesaunderson** [comment]
We are also having the same errors, did you solve this?

**Comment by rowanhill** [comment]
Firstly, sorry for taking so long to reply!

As for your issue... It does sound like the WireMock\Client\WireMock class in PHP is failing to connect to a running WireMock server. Can I check that you're running a standalone version of wiremock before executing that PHP script?

**Comment by rowanhill** [comment]
I'm going to close this issue (at least for now) as I suspect it's not a live issue for either of you - again, apologies for not responding when you first raised it.

If you (or anyone else) does see this problem again, feel free to comment.
