### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by kasperg** [rowanhill/wiremock-php#15]
Thanks for sharing wiremock-php!

I ran into a problem when trying to set up the project. I use `StubImportBuilder` to import serialized stubs. Originally these stubs did not have an `id` set so I just set a random value. The code ran fine but WireMock did not behave as expected. When stepping through the code I discovered that WireMock had returned an error response to the Curl request explaining that my stub ids were malformed. WireMock expected them to be UUIDs. 

I discoveted that `wiremock-php` never checks the result of the request but simply returns. In my situation debugging would have been easier if an exception had been thrown or the like.

Is the current behavior intentional? Would you consider a PR adding some form of error handling?

**Comment by rowanhill** [comment]
Hi Kasper! To be honest, I haven't used wiremock-php myself for several years, so my memory is a little hazy. It does look to me like it's just an oversight though - and in fact, there seem to a be few places where the code is ignoring the result of a POST/PUT to the WireMock API (in WireMock.php) that ought to be handling errors more explicitly.

A PR adding some error handling would be delightful - ideally it'd cover all those places in WireMock.php, but even just in importStubs would be a great start. If you do take a look at this, I'd really appreciate it if we could add some tests that cover this behaviour.

Thanks!

**Comment by kasperg** [comment]
Thanks for the followup, Rowan. 

I will look into a PR if I get the time.

**Comment by rowanhill** [comment]
FYI, I've now added some simple error handling in the Curl class - if WireMock responds with a non-2xx a ClientException is thrown (with some details pulled out of the response if possible). I think that would have helped your debugging, and should do a good job of catching other similar errors elsewhere.

**Comment by kasperg** [comment]
:+1: The recent updates look great!
