### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by stevenbrookes** [rowanhill/wiremock-php#16]
Hi Rowan

Thanks for building this library.  I'd like to make use of the webhooks extension described here   http://wiremock.org/docs/webhooks-and-callbacks/   I don't see function that does the withPostServeAction call that's mentioned for the java binding.  Is it possible to do with the current library?  Or hard to add?

Thanks

Steve

**Comment by rowanhill** [comment]
Hi Steve,

Sorry it's taken me a while to get around to this, but I've made my way up to 2.30 compatibility - which means webhooks and withPostServeAction should be available for you now (once you update wiremock-php to 2.30.0).

I hope it's still useful!

Thanks,
Rowan

**Comment by stevenbrookes** [comment]
Hi Rowan

Happy New Year!  Thanks for adding that I'll give it a spin next week.

Steve
