### ISSUE TITLE
Support Symfony5.4+

### ISSUE THREAD

**Issue by qdequippe** [rowanhill/wiremock-php#17]
Hi,

Did you plan any support for Symfony 5.4+ dependencies? Or may I contribute?

Regards

**Comment by rowanhill** [comment]
Hi Quentin,

Symfony 5.4 requires PHP 7.2, but right now (according to packagist.org) about 16% of wiremock-php downloads are for <= 7.1.

I'd like to raise the minimum version of PHP required to 7.2, just for the developer comforts that brings, but it seems like that would cause a problem for more users than I'm comfortable with for now.

Do you have any compatibility issues using current wiremock-php with Symfony 5.4+?

Thanks,
Rowan

**Comment by qdequippe** [comment]
Hi @rowanhill 

wiremock-php already requires PHP 7.2 https://github.com/rowanhill/wiremock-php/blob/master/composer.json#L32 isn't it?

> Do you have any compatibility issues using current wiremock-php with Symfony 5.4+?
Maybe I am wrong but I can't use wiremock-php with Symfony 5.4+ because it's defined ^4.4 in the composer.json https://github.com/rowanhill/wiremock-php/blob/master/composer.json#L33

**Comment by rowanhill** [comment]
Hi Quentin,

Sorry, you're quite right. As of the latest release (2.33), wiremock-php does require PHP 7.2 - I'd forgotten that change was in there. I'm not certain it was the best choice, given the percentage of downloads for 2.32 that are still PHP 7.1 (18.6%, as of this week).

2.33 is also the first release with a dependency on Symfony. It's being used for (de)serialization, which was previously just hand rolled. Maybe that also wasn't such a great choice, given there are 3 major versions in support at the moment.

Although it's a bit painful, I think the best choice might be to roll back the recent changes and re-implement the 2.33 release based off the 2.32 code (with no Symfony dependency).

I'm not likely to get around to that very soon, but if your immediate need is to use wiremock-php with Symfony 5.4, I'd suggest just using version 2.32 of wiremock-php - there are very few features in 2.33 that aren't in 2.32!

Thanks,
Rowan

**Comment by qdequippe** [comment]
Hi @rowanhill,

I hadn't thought to check previous versions, thanks for the advice I will stick to the 2.32 :)

Regards,
Quentin

**Comment by rowanhill** [comment]
Hi @qdequippe,

I've had a go at implementing something that doesn't depend on Symfony. If you had time, I'd appreciate it if you could give it a try by updating your composer dependency version to "dev-custom-serde" (to use the custom-serde branch of GitHub) and let me know if you have any problems. It's quite a large change, so I'm keen to get a bit of feedback before releasing it, if possible!

Thanks,
Rowan

**Comment by rowanhill** [comment]
Hmm, that's strange. I don't _think_ it will be related to these changes.

I did a quick test, and it seemed okay for me. I created an empty project, and added the dependency, so composer.json looked like this:

```json
{
    "name": "rowan/wiremockphptest",
    "type": "project",
    "autoload": {
        "psr-4": {
            "Rowan\\Wiremockphptest\\": "src/"
        }
    },
    "require": {
        "wiremock-php/wiremock-php": "dev-custom-serde"
    }
}
```

I then added a simple index.php  based on the example in the README like this:

```php
<?php
  
require __DIR__ . '/../vendor/autoload.php';

use WireMock\Client\WireMock;

// Create an object to administer a WireMock instance. This is assumed to be at
// localhost:8080 unless these values are overridden.
$wireMock = WireMock::create(/* specify host, port here if needed */);

// Stub out a request
$wireMock->stubFor(WireMock::get(WireMock::urlEqualTo('/some/url'))
    ->willReturn(WireMock::aResponse()
        ->withHeader('Content-Type', 'text/plain')
        ->withBody('Hello world!')));

// Verify a request
$wireMock->verify(WireMock::postRequestedFor(WireMock::urlEqualTo('/verify/this'))
    ->withHeader('Content-Type', WireMock::equalTo('text/xml')));

echo "Done\n";
```

That all seemed to behave as expected - it threw an exception because I didn't actually have wiremock running, but the WireMock class was available.
