### ISSUE TITLE
Recording feature

### ISSUE THREAD

**Issue by eliysha** [rowanhill/wiremock-php#3]
Hey,

Are you planning to add recording feature introduced [here](https://github.com/tomakehurst/wiremock/pull/674) ?

**Comment by zonk911** [comment]
oh no i don't plan to do so

**Comment by rowanhill** [comment]
Hi - sorry it's been a long wait, but the short answer is, now: yes!

I'm adding a whole boatload of new features to bring this library up to date with modern WireMock, and I just got around to adding the recording features - see #5 for more details, and feel free to comment there if you see any issues with the work-in-progress.
